baseURL = "https://verifyvalley.github.io"
languageCode = "en-us"
theme = "raditian"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "Objectifs"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Acteurs"
  URL = "#portfolio"
  weight = 3

  [[menu.header]]
  name = "Partenaires"
  URL = "#contact"
  weight = 4


  [[menu.footer]]
     name = "Objectifs"
     URL = "#about"
     weight = 2

  [[menu.footer]]
   name = "Acteurs"
   URL = "#portfolio"
   weight = 3

  [[menu.footer]]
  name = "Partenaires"
  URL = "#contact"
  weight = 4



[params]

  sections = ["showcase", "about", "education", "experience", "client-and-work","partners", "events","testimonial", "contact", "newsletter"]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Verify"
    text2 = "Valley"

  [params.footer]
      copyright = "Verify Valley"
      #[params.footer.radity_logo]
      #  x = "img/general/design-and-code-radity.png"
      #  _2x = "img/general/design-and-code-radity@2x.png"
      #  alt = "Design & Code - Radity"
